'use client';

import { useEffect, useMemo, useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowLeft, Baby, Bath, Bell, Bot, BrushCleaning, Bubbles, Camera, Droplets, Eye, FlaskConical, Footprints, Hand, Heart, Leaf, Menu, MessageCircle, Minus, PackagePlus, Pipette, Plus, RefreshCw, Scissors, Search, Send, ShieldCheck, ShoppingBag, Smile, Sparkles, SprayCan, Star, Sun, Trash2, Truck, X } from 'lucide-react';
import { getSupabase } from '@/lib/supabase';
import { ImageSearch } from '@/app/image-search';

declare global { interface Document { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } } }

type Product = { id: string; name: string; category: string; price: number; oldPrice?: number; stock: number; image: string; description: string; featured?: boolean };
type StoreCategory = { id:string; name:string; sort_order:number; parent_id?:string|null };
type Order = { id:string; customer_name:string; phone:string; address:string; notes:string; total:number; items:{name:string;qty:number}[]; status:string; created_at:string };
type Policy = 'privacy'|'returns'|'terms'|null;
const deliveryAreas=[{name:'داخل بغداد',fee:5000},{name:'محافظات العراق',fee:8000}];
const initialProducts: Product[] = [
  { id:'1', name:'واقي شمس فيوجن ووتر', category:'واقيات الشمس', price:40000, oldPrice:45000, stock:18, image:'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=700&q=80', description:'حماية يومية عالية وخفيفة على البشرة، مناسبة للاستخدام تحت المكياج.', featured:true },
  { id:'2', name:'سيروم فيتامين C للإشراقة', category:'سيرومات', price:50000, oldPrice:58000, stock:12, image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=700&q=80', description:'سيروم مركز يمنح البشرة إشراقة ويوحد مظهر لونها.', featured:true },
  { id:'3', name:'كريم ترطيب عميق', category:'مرطبات', price:32000, stock:25, image:'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=700&q=80', description:'ترطيب طويل المفعول بتركيبة مريحة للبشرة الحساسة.' },
  { id:'4', name:'غسول لطيف للبشرة', category:'غسولات', price:28000, oldPrice:33000, stock:9, image:'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=700&q=80', description:'ينظف الشوائب بلطف ويحافظ على توازن البشرة الطبيعي.' },
  { id:'5', name:'روتين العناية المتكامل', category:'العناية بالبشرة', price:76000, oldPrice:89000, stock:7, image:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=700&q=80', description:'ثلاث خطوات يومية لبشرة صحية ومشرقة.' },
  { id:'6', name:'بلسم إصلاح الشعر', category:'العناية بالشعر', price:36000, stock:16, image:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=700&q=80', description:'بلسم مغذٍ يساعد على تقليل الجفاف والتقصف.' },
];
const money = (n:number) => new Intl.NumberFormat('ar-IQ').format(n) + ' د.ع';
const HairIcon = ({className}:{className?:string}) => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true"><path d="M12 3.25c-4.4 0-7.25 3.15-7.25 7.45 0 3.9 1.35 7.35 3.45 10.05"/><path d="M12 3.25c4.4 0 7.25 3.15 7.25 7.45 0 3.9-1.35 7.35-3.45 10.05"/><path d="M12 3.75v17"/><path d="M9.65 5.15c-1.8 2.4-2.25 5.15-1.55 8.25.55 2.4.45 4.65-.25 6.75"/><path d="M14.35 5.15c1.8 2.4 2.25 5.15 1.55 8.25-.55 2.4-.45 4.65.25 6.75"/><path d="M6.15 8.15c1.55.15 3.65-.55 5.85-4.4 2.2 3.85 4.3 4.55 5.85 4.4"/></svg>;
const skinCategoryNames = ['غسولات','مرطبات','واقيات الشمس','سيرومات','مزيلات المكياج','تونر'];
const primaryCategoryNames = ['العناية بالبشرة','العناية بالشعر','العناية بالأظافر','العناية بالأطفال','العناية بالجسم','العناية بالفم','العناية بالقدم','العناية باليد','أنواع المينوكسيديل','العناية بالشفاه','العناية بالحواجب والرموش'];
const defaultCategoryNames = [...primaryCategoryNames,...skinCategoryNames];
const categoryIconMap:Record<string,typeof Sparkles> = {
  'العناية بالبشرة':Sparkles,
  'غسولات':Bubbles,
  'مرطبات':Droplets,
  'واقيات الشمس':Sun,
  'سيرومات':FlaskConical,
  'مزيلات المكياج':BrushCleaning,
  'تونر':SprayCan,
  'العناية بالشعر':Scissors,
  'العناية بالأظافر':Hand,
  'العناية بالأطفال':Baby,
  'العناية بالجسم':Bath,
  'العناية بالفم':Smile,
  'العناية بالقدم':Footprints,
  'العناية باليد':Hand,
  'أنواع المينوكسيديل':Pipette,
  'العناية بالشفاه':Heart,
  'العناية بالحواجب والرموش':Eye,
  'الكل':PackagePlus,
};
const PAGE_SIZE = 24;
const mapProduct = (p:Record<string,unknown>):Product => ({
  ...(p as unknown as Product),
  oldPrice:p.old_price ? Number(p.old_price) : undefined,
  price:Number(p.price),
  stock:Number(p.stock),
});

export default function Home() {
  const reduceMotion=useReducedMotion();
  const [view,setView] = useState<'store'|'admin'>('store');
  const [products,setProducts] = useState<Product[]>(initialProducts);
  const [catalogProducts,setCatalogProducts] = useState<Product[]>(initialProducts);
  const [hasMore,setHasMore] = useState(false);
  const [loadingProducts,setLoadingProducts] = useState(false);
  const [storeCategories,setStoreCategories] = useState<StoreCategory[]>([]);
  const [query,setQuery] = useState(''); const [category,setCategory] = useState('الكل');
  const [expandedCategory,setExpandedCategory] = useState<string|null>(null);
  const [cart,setCart] = useState<Record<string,number>>({}); const [cartOpen,setCartOpen] = useState(false);
  const [checkoutOpen,setCheckoutOpen] = useState(false);
  const [selected,setSelected] = useState<Product|null>(null);
  const [adminOpen,setAdminOpen] = useState(false); const [notice,setNotice] = useState('');
  const [chatOpen,setChatOpen] = useState(false);
  const [policy,setPolicy]=useState<Policy>(null);
  const [,setBrandTaps]=useState(0);
  useEffect(()=>{try{const saved=localStorage.getItem('hayat-cart');if(saved)setCart(JSON.parse(saved))}catch{}},[]);
  useEffect(()=>{localStorage.setItem('hayat-cart',JSON.stringify(cart))},[cart]);
  useEffect(()=>{void getSupabase().then(client=>client.from('store_categories').select('*').order('sort_order')).then(({data})=>{if(data)setStoreCategories(data as StoreCategory[])})},[]);
  useEffect(()=>{const timer=setTimeout(()=>{void (async()=>{setLoadingProducts(true);const client=await getSupabase();const {data,error}=await client.rpc('catalog_products',{search_text:query.trim()||null,category_filter:category==='الكل'?null:category,page_size:PAGE_SIZE,page_offset:0});setLoadingProducts(false);if(error)return;const rows=((data||[]) as Record<string,unknown>[]).map(mapProduct);setCatalogProducts(rows);setHasMore(rows.length===PAGE_SIZE);setProducts(current=>{const merged=new Map(current.map(p=>[p.id,p]));rows.forEach(p=>merged.set(p.id,p));return [...merged.values()]})})()},250);return()=>clearTimeout(timer)},[query,category]);
  const loadMore=async()=>{if(loadingProducts||!hasMore)return;setLoadingProducts(true);const client=await getSupabase();const {data,error}=await client.rpc('catalog_products',{search_text:query.trim()||null,category_filter:category==='الكل'?null:category,page_size:PAGE_SIZE,page_offset:catalogProducts.length});setLoadingProducts(false);if(error)return;const rows=((data||[]) as Record<string,unknown>[]).map(mapProduct);setCatalogProducts(current=>[...current,...rows]);setHasMore(rows.length===PAGE_SIZE);setProducts(current=>{const merged=new Map(current.map(p=>[p.id,p]));rows.forEach(p=>merged.set(p.id,p));return [...merged.values()]})};
  useEffect(()=>{ if(notice){const t=setTimeout(()=>setNotice(''),2400);return()=>clearTimeout(t)} },[notice]);
  const save=async(next:Product[],adminToken:string)=>{const changed=next.find(p=>!products.some(old=>JSON.stringify(old)===JSON.stringify(p)));if(!changed)return;const client=await getSupabase();const {error}=await client.rpc('admin_save_product',{session_token:adminToken,payload:changed});if(error){setNotice('انتهت جلسة الإدارة، ادخل مجددًا');return}setProducts(next);setCatalogProducts(current=>[changed,...current.filter(p=>p.id!==changed.id)]);setNotice('تم حفظ المنتج')};
  const remove=async(id:string,adminToken:string)=>{if(!window.confirm('هل تريد حذف هذا المنتج نهائيًا؟'))return;const client=await getSupabase();const {error}=await client.rpc('admin_delete_product',{session_token:adminToken,product_id:id});if(error){setNotice('انتهت جلسة الإدارة، ادخل مجددًا');return}setProducts(current=>current.filter(p=>p.id!==id));setCatalogProducts(current=>current.filter(p=>p.id!==id))};
  const saveCategory=async(category:Partial<StoreCategory>,adminToken:string)=>{const previous=storeCategories.find(c=>c.id===category.id);const client=await getSupabase();const {data,error}=await client.rpc('admin_save_category',{session_token:adminToken,payload:category});if(error){setNotice(error.message.includes('duplicate')?'اسم القسم مستخدم مسبقًا':'تعذر حفظ القسم');return false}const saved=data as StoreCategory;setStoreCategories(current=>[...current.filter(c=>c.id!==saved.id),saved].sort((a,b)=>a.sort_order-b.sort_order));if(previous&&previous.name!==saved.name)setProducts(current=>current.map(p=>p.category===previous.name?{...p,category:saved.name}:p));setNotice(previous?'تم تعديل القسم':'تمت إضافة القسم');return true};
  const deleteCategory=async(id:string,adminToken:string)=>{const client=await getSupabase();const {error}=await client.rpc('admin_delete_category',{session_token:adminToken,category_id:id});if(error){setNotice(error.message.includes('category in use')?'لا يمكن حذف قسم يحتوي منتجات':'تعذر حذف القسم');return}setStoreCategories(current=>current.filter(c=>c.id!==id));setNotice('تم حذف القسم')};
  useEffect(()=>{
    if(!document.modelContext?.registerTool) return;
    const lifecycle=new AbortController();
    void Promise.resolve(document.modelContext.registerTool({
      name:'add_store_product', title:'إضافة منتج', description:'إضافة منتج جديد إلى صيدلية حياة المجد وعرضه مباشرة في قائمة المنتجات.',
      inputSchema:{type:'object',properties:{name:{type:'string'},category:{type:'string'},price:{type:'number'},stock:{type:'number'},image:{type:'string'},description:{type:'string'}},required:['name','category','price','stock','image'],additionalProperties:false},
      annotations:{readOnlyHint:false,untrustedContentHint:false},
      execute(input:unknown){ const x=input as Partial<Product>; if(!x.name||!x.category||!x.image||typeof x.price!=='number'||x.price<=0||typeof x.stock!=='number'||x.stock<0) throw new Error('بيانات المنتج غير صالحة'); const p:Product={id:crypto.randomUUID(),name:x.name,category:x.category,price:x.price,stock:x.stock,image:x.image,description:x.description||''}; setProducts(current=>{const next=[p,...current];localStorage.setItem('hayat-products',JSON.stringify(next));return next}); return {id:p.id,status:'created',name:p.name}; }
    },{signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[]);
  const categoryNames=storeCategories.length?storeCategories.map(c=>c.name):defaultCategoryNames;
  const topCategoryNames=primaryCategoryNames;
  const childCategoryNames=expandedCategory==='العناية بالبشرة'?skinCategoryNames:[];
  const categories=['الكل',...categoryNames];
  const filtered=catalogProducts;
  const cartItems=Object.entries(cart).map(([id,qty])=>({product:products.find(p=>p.id===id)!,qty})).filter(x=>x.product);
  const total=cartItems.reduce((s,x)=>s+x.product.price*x.qty,0); const count=Object.values(cart).reduce((a,b)=>a+b,0);
  const add=(id:string)=>{const product=products.find(p=>p.id===id);if(!product||product.stock<1){setNotice('هذا المنتج غير متوفر حاليًا');return}setCart(c=>({...c,[id]:Math.min(product.stock,(c[id]||0)+1)}));setNotice('تمت إضافة المنتج إلى السلة')};
  return <main dir="rtl" className="premium-shell min-h-screen text-[#0a315c]">
    <header className="premium-header sticky top-0 z-40"><div className="mx-auto flex h-16 max-w-7xl items-center gap-2 px-3 md:h-20 md:gap-4 md:px-8">
      <button onClick={()=>setAdminOpen(!adminOpen)} className="md:hidden" aria-label="القائمة"><Menu/></button>
      <button onClick={()=>{setView('store');setBrandTaps(n=>{const next=n+1;if(next>=6){setView('admin');setCategory('الكل');setQuery('');setAdminOpen(false);return 0}return next})}} className="flex min-w-0 items-center gap-2 md:gap-3"><img src="/hayat-almajd-logo-small.png" width="160" height="160" alt="شعار صيدلية حياة المجد" className="h-11 w-11 shrink-0 rounded-full border border-[#bfdbfe]/30 bg-white object-cover shadow-sm md:h-14 md:w-14"/><span className="min-w-0 text-right leading-tight"><b className="block whitespace-nowrap text-sm md:text-lg">صيدلية حياة المجد</b><small className="hidden whitespace-nowrap text-[#168bc5] sm:block">عناية تثق بها</small></span></button>
      <div className="relative mx-auto hidden w-full max-w-lg md:block"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-blue-400" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج..." className="w-full rounded-2xl border border-blue-100 bg-blue-50/60 py-3 pr-12 pl-4 outline-none focus:border-blue-400"/></div>
      <nav className={`${adminOpen?'flex':'hidden'} absolute right-4 top-20 flex-col gap-2 rounded-2xl bg-white p-3 shadow-xl md:static md:flex md:flex-row md:bg-transparent md:p-0 md:shadow-none`}><button onClick={()=>{setView('store');setAdminOpen(false)}} className={`rounded-xl px-4 py-2 font-bold ${view==='store'?'bg-blue-50 text-[#087cc1]':''}`}>المتجر</button></nav>
      {view==='store'&&<ImageSearch onChoose={product=>{setProducts(current=>current.some(item=>item.id===product.id)?current:[product,...current]);setSelected(product)}}/>}
      <button onClick={()=>setCartOpen(true)} className="relative mr-auto grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#0b4b84] text-white md:mr-0 md:h-11 md:w-11" aria-label="السلة"><ShoppingBag size={20}/>{count>0&&<span className="absolute -left-2 -top-2 grid h-6 min-w-6 place-items-center rounded-full bg-[#168bc5] px-1 text-xs font-bold">{count}</span>}</button>
    </div><div className="mobile-search-wrap mx-auto max-w-7xl px-3 pb-3 md:hidden"><div className="relative"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-[#168bc5]" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج..." aria-label="البحث عن منتج" className="mobile-search-input w-full rounded-2xl py-3 pr-11 pl-4 outline-none"/></div></div></header>
    {view==='store'?<>
      <motion.section initial={reduceMotion?{opacity:0}:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.75,ease:[.22,1,.36,1]}} className="storefront-hero mx-auto max-w-7xl px-4 pt-5 md:px-8 md:pt-8">
        <div className="hero-panel premium-hero relative min-h-[430px] overflow-hidden rounded-[2.4rem] bg-[#dceeff] md:min-h-[570px]">
          <img src="/hayat-hero-products-mini.jpg" alt="مجموعة منتجات عناية من صيدلية حياة المجد" width="900" height="506" loading="eager" fetchPriority="high" decoding="async" className="absolute inset-0 h-full w-full object-cover object-[65%_center]"/>
          <div className="hero-wash absolute inset-0"/>
          <div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/>
          <div className="relative z-10 flex min-h-[430px] max-w-[670px] flex-col justify-center p-7 md:min-h-[570px] md:p-16">
            <motion.span initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.18,duration:.45}} className="premium-pill mb-6 w-fit">صيدلية عصرية • عناية موثوقة</motion.span>
            <motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.25,duration:.65,ease:[.22,1,.36,1]}} className="hero-title text-4xl font-black leading-[1.13] text-[#071d35] md:text-7xl">العناية تبدأ<br/><span>من اختيار أذكى.</span></motion.h1>
            <motion.p initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.55}} className="mt-6 max-w-lg text-base leading-8 text-[#365b7d] md:text-xl">تجربة صيدلانية راقية تجمع منتجات أصلية، تفاصيل واضحة، وتسوقًا سلسًا مصممًا حول احتياجك.</motion.p>
            <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.45,duration:.5}} className="mt-8 flex flex-wrap gap-3"><motion.button whileHover={reduceMotion?{}:{scale:1.025,y:-2}} whileTap={{scale:.98}} onClick={()=>document.getElementById('products')?.scrollIntoView({behavior:'smooth'})} className="premium-cta inline-flex items-center gap-2 rounded-full px-8 py-4 font-black text-white">اكتشف المجموعة <ArrowLeft size={18}/></motion.button><motion.button whileHover={reduceMotion?{}:{y:-2}} onClick={()=>setChatOpen(true)} className="premium-ghost rounded-full px-7 py-4 font-bold">اسأل المساعد <Sparkles size={17}/></motion.button></motion.div>
          </div>
        </div>
        <div className="benefit-strip premium-benefits relative z-20 mx-3 -mt-8 grid grid-cols-2 overflow-hidden rounded-[1.7rem] md:mx-12 md:grid-cols-4">
          {[{icon:Leaf,title:'مختارة بعناية',text:'منتجات أصلية'},{icon:ShieldCheck,title:'جودة موثوقة',text:'مصادر معتمدة'},{icon:Truck,title:'توصيل سريع',text:'إلى جميع المحافظات'},{icon:RefreshCw,title:'خدمة مرنة',text:'استبدال سهل'}].map(({icon:Icon,title,text},i)=><motion.div initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}} key={title} className="flex items-center gap-3 p-4 md:p-5"><span className="benefit-icon grid h-11 w-11 shrink-0 place-items-center rounded-2xl"><Icon size={21}/></span><span><b className="block text-sm text-[#17466f]">{title}</b><small className="text-slate-500">{text}</small></span></motion.div>)}
        </div>
      </motion.section>
      <motion.section initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65,ease:[.22,1,.36,1]}} className="premium-bento mx-auto grid max-w-7xl gap-4 px-4 pt-16 md:grid-cols-12 md:px-8 md:pt-24"><div className="bento-card bento-dark md:col-span-7"><span className="bento-kicker">اختيار أدق</span><h2>كل ما تحتاجه.<br/>في مكان واحد.</h2><p>اكتشف منتجات العناية حسب احتياجك، مع معلومات واضحة وأسعار محدثة.</p><div className="bento-shine"/></div><div className="bento-card bento-light md:col-span-5"><span className="bento-icon"><ShieldCheck/></span><h3>أصلي. موثوق.<br/>بدون تنازلات.</h3><p>اختيارات صيدلانية من مصادر معتمدة.</p></div><div className="bento-card bento-soft md:col-span-4"><span className="bento-icon"><Truck/></span><h3>يوصل إليك بسرعة</h3><p>توصيل منظم لجميع محافظات العراق.</p></div><div className="bento-card bento-gradient md:col-span-8"><span className="bento-kicker">مساعد حياة المجد</span><h3>اسأل. اكتشف. اختر بثقة.</h3><p>واجهة مساعد ذكي جاهزة لتوجيهك نحو المنتج الأنسب.</p><button onClick={()=>setChatOpen(true)}>ابدأ المحادثة <ArrowLeft size={16}/></button></div></motion.section>
      <motion.section initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.6}} className="mx-auto max-w-7xl px-4 pb-4 pt-16 md:px-8 md:pt-24"><div className="mb-8 text-center"><span className="premium-section-label">مختار لك بعناية</span><h2 className="premium-section-title mt-2 text-4xl font-black text-[#071d35] md:text-5xl">تسوّق حسب اهتمامك</h2><p className="mx-auto mt-3 max-w-xl text-slate-500">تنقّل بسهولة بين مجموعاتنا المصممة لكل تفاصيل العناية اليومية.</p></div><div className="category-rail overflow-x-auto pb-4"><div className="flex min-w-max gap-3 md:gap-5">{['الكل',...topCategoryNames].map((name,i)=>{const Icon=categoryIconMap[name]||PackagePlus;const hasChildren=name==='العناية بالبشرة';const active=category===name||expandedCategory===name;return <motion.button initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:Math.min(i*.035,.3)}} whileHover={reduceMotion?{}:{y:-7}} key={name} onClick={()=>{if(hasChildren){setExpandedCategory(expandedCategory===name?null:name);setCategory('الكل');return}setExpandedCategory(null);setCategory(name);document.getElementById('products')?.scrollIntoView({behavior:'smooth',block:'start'})}} className={`category-tile premium-category group w-[132px] shrink-0 rounded-[1.8rem] border p-3 md:w-[154px] ${active?'active-category':'border-white/70 bg-white/85'}`}><span className="mx-auto grid aspect-square w-full max-w-[88px] place-items-center rounded-full text-[#168bc5]">{name==='العناية بالشعر'?<HairIcon className="h-9 w-9 md:h-11 md:w-11"/>:<Icon className="h-8 w-8 md:h-10 md:w-10"/>}</span><b className="mt-3 block text-sm text-[#17466f] md:text-base">{name==='الكل'?'كل المنتجات':name}</b></motion.button>})}</div></div>{childCategoryNames.length>0&&<div className="mt-4 rounded-2xl border border-blue-100 bg-white/80 p-3 backdrop-blur-xl"><p className="mb-2 text-sm font-bold text-[#17466f]">أقسام العناية بالبشرة</p><div className="flex gap-2 overflow-x-auto pb-1">{childCategoryNames.map(name=><button key={name} onClick={()=>{setCategory(name);document.getElementById('products')?.scrollIntoView({behavior:'smooth'})}} className={`shrink-0 rounded-full px-5 py-2.5 text-sm font-bold ${category===name?'bg-[#0b4b84] text-white':'bg-blue-50 text-[#17466f]'}`}>{name}</button>)}</div></div>}</motion.section>
      <section id="products" className="mx-auto max-w-7xl px-4 pb-20 pt-10 md:px-8"><div className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="text-sm font-bold text-[#168bc5]">الأكثر طلبًا</span><h2 className="mt-1 text-3xl font-black text-[#0a315c]">منتجات مميزة</h2></div><div className="flex gap-2 overflow-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold ${category===c?'bg-[#0b4b84] text-white':'border border-blue-100 bg-white text-[#17466f]'}`}>{c}</button>)}</div></div><div className="mb-5 md:hidden"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج..." className="w-full rounded-2xl border border-blue-100 bg-white px-4 py-3"/></div>
      {filtered.length?<><div className="grid grid-cols-2 gap-4 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(p=><article key={p.id} onClick={()=>setSelected(p)} className="group cursor-pointer overflow-hidden rounded-[1.6rem] border border-blue-50 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-square overflow-hidden bg-[#eef8fd]"><img src={p.image.replace('q=80','q=82')} alt={p.name} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><button onClick={e=>e.stopPropagation()} className="absolute left-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-slate-500"><Heart size={17}/></button>{p.oldPrice&&<span className="absolute right-3 top-3 rounded-full bg-[#168bc5] px-3 py-1 text-xs font-bold text-white">عرض</span>}</div><div className="p-4"><small className="text-[#168bc5]">{p.category}</small><h3 className="mt-1 min-h-12 text-base font-black md:text-lg">{p.name}</h3><div className="mt-2 flex items-center gap-1 text-[#3b82f6]"><Star size={14} fill="currentColor"/><span className="text-xs text-slate-500">4.9</span></div><div className="mt-4 flex items-end justify-between gap-2"><div><b className="block text-base md:text-lg">{money(p.price)}</b>{p.oldPrice&&<del className="text-xs text-slate-400">{money(p.oldPrice)}</del>}</div><button onClick={e=>{e.stopPropagation();add(p.id)}} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#0b4b84] text-white hover:bg-[#0c8cca]" aria-label={`أضف ${p.name}`}><Plus/></button></div></div></article>)}</div>{hasMore&&<div className="mt-8 text-center"><button onClick={()=>void loadMore()} disabled={loadingProducts} className="rounded-full bg-[#0b4b84] px-8 py-3 font-black text-white disabled:opacity-60">{loadingProducts?'جارٍ التحميل...':'عرض منتجات أكثر'}</button></div>}</>:<div className="rounded-3xl bg-white p-12 text-center"><Search className="mx-auto text-blue-300" size={40}/><h3 className="mt-3 text-xl font-bold">لا توجد نتائج</h3></div>}</section>
    </>:<Admin products={catalogProducts} categories={storeCategories} hasMore={hasMore} loadingProducts={loadingProducts} onLoadMore={loadMore} onSearch={setQuery} onSave={save} onDelete={remove} onSaveCategory={saveCategory} onDeleteCategory={deleteCategory}/>}
    {cartOpen&&<div className="fixed inset-0 z-50 bg-slate-950/35" onClick={()=>setCartOpen(false)}><aside onClick={e=>e.stopPropagation()} className="mr-auto flex h-full w-full max-w-md flex-col bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">سلة التسوق</h2><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="mt-8 flex-1 space-y-4 overflow-auto">{cartItems.length?cartItems.map(({product:p,qty})=><div key={p.id} className="flex gap-3 rounded-2xl border border-blue-100 p-3"><img src={p.image} alt="" className="h-20 w-20 rounded-xl object-cover"/><div className="flex-1"><b>{p.name}</b><p className="mt-1 text-sm text-[#168bc5]">{money(p.price)}</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,qty-1)}))}><Minus size={16}/></button><span>{qty}</span><button onClick={()=>add(p.id)}><Plus size={16}/></button></div></div><button onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}><Trash2 size={18} className="text-red-400"/></button></div>):<div className="py-20 text-center text-slate-400"><ShoppingBag className="mx-auto mb-3" size={44}/>السلة فارغة</div>}</div><div className="border-t pt-5"><div className="flex justify-between text-xl font-black"><span>الإجمالي</span><span>{money(total)}</span></div><button disabled={!cartItems.length} onClick={()=>setCheckoutOpen(true)} className="mt-5 w-full rounded-2xl bg-[#0b4b84] py-4 font-black text-white disabled:opacity-40">إتمام الطلب</button></div></aside></div>}
    {checkoutOpen&&<Checkout items={cartItems} total={total} onClose={()=>setCheckoutOpen(false)} onSuccess={id=>{setCheckoutOpen(false);setCartOpen(false);setCart({});setNotice(`تم تسجيل الطلب رقم ${id.slice(0,8)}`)}}/>}
    {selected&&<div className="fixed inset-0 z-50 bg-slate-950/40 backdrop-blur-sm" onClick={()=>setSelected(null)}><aside onClick={e=>e.stopPropagation()} className="product-drawer h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><div className="relative aspect-[5/4] overflow-hidden bg-blue-50"><img src={selected.image.replace('w=700','w=1200').replace('q=80','q=95')} alt={selected.name} className="h-full w-full object-cover"/><button onClick={()=>setSelected(null)} className="absolute left-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/95 shadow-lg" aria-label="إغلاق"><X/></button>{selected.oldPrice&&<span className="absolute right-5 top-5 rounded-full bg-[#168bc5] px-4 py-2 font-bold text-white">عرض خاص</span>}</div><div className="p-7 md:p-9"><span className="text-sm font-bold text-[#168bc5]">{selected.category}</span><h2 className="mt-2 text-3xl font-black md:text-4xl">{selected.name}</h2><div className="mt-4 flex items-center gap-2 text-[#3b82f6]"><Star fill="currentColor" size={18}/><Star fill="currentColor" size={18}/><Star fill="currentColor" size={18}/><Star fill="currentColor" size={18}/><Star fill="currentColor" size={18}/><span className="mr-2 text-sm text-slate-500">4.9 (128 تقييم)</span></div><p className="mt-6 text-lg leading-8 text-slate-600">{selected.description}</p><div className="mt-6 rounded-2xl bg-blue-50/70 p-4"><div className="flex items-center justify-between"><span className="text-slate-500">التوفر</span><b className="text-emerald-600">متوفر • {selected.stock} قطعة</b></div></div><div className="mt-7 flex items-end justify-between"><div><small className="text-slate-500">السعر</small><b className="block text-3xl">{money(selected.price)}</b>{selected.oldPrice&&<del className="text-slate-400">{money(selected.oldPrice)}</del>}</div></div><button onClick={()=>{add(selected.id);setSelected(null);setCartOpen(true)}} className="mt-7 flex w-full items-center justify-center gap-3 rounded-2xl bg-[#0b4b84] py-4 text-lg font-black text-white shadow-xl shadow-blue-200"><ShoppingBag/> أضف إلى السلة</button><div className="mt-5 flex items-center justify-center gap-2 text-sm text-slate-500"><Truck size={18}/> توصيل سريع وآمن حتى باب المنزل</div></div></aside></div>}
    {notice&&<div className="fixed bottom-5 left-1/2 z-[60] -translate-x-1/2 rounded-full bg-[#073763] px-6 py-3 font-bold text-white shadow-2xl">{notice}</div>}
    {view==='store'&&<><button onClick={()=>setChatOpen(true)} aria-label="فتح المساعد الذكي" className="fixed bottom-24 right-4 z-30 grid h-14 w-14 place-items-center rounded-full bg-[#0b4b84] text-white shadow-xl shadow-blue-900/20 transition hover:scale-105"><Bot/></button><a href={`https://wa.me/?text=${encodeURIComponent('مرحباً، أريد الاستفسار عن منتجات صيدلية حياة المجد')}`} target="_blank" rel="noreferrer" aria-label="تواصل عبر واتساب" className="fixed bottom-5 right-4 z-30 grid h-14 w-14 place-items-center rounded-full bg-[#25D366] text-white shadow-xl transition hover:scale-105"><MessageCircle/></a><footer className="border-t border-blue-100 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-10 md:grid-cols-3 md:px-8"><div><div className="flex items-center gap-3"><img src="/hayat-almajd-logo.png" alt="" className="h-14 w-14 rounded-full border border-[#bfdbfe]/30 object-cover"/><b className="text-xl">صيدلية حياة المجد</b></div><p className="mt-2 max-w-sm leading-7 text-slate-500">منتجات عناية أصلية وخدمة توصيل لجميع محافظات العراق.</p></div><div><b>خدمة العملاء</b><p className="mt-2 text-sm leading-7 text-slate-500">الدفع عند الاستلام<br/>تأكيد الطلبات عبر الهاتف</p></div><div><b>معلومات مهمة</b><div className="mt-2 flex flex-col items-start gap-2 text-sm text-[#168bc5]"><button onClick={()=>setPolicy('privacy')}>سياسة الخصوصية</button><button onClick={()=>setPolicy('returns')}>الاستبدال والاسترجاع</button><button onClick={()=>setPolicy('terms')}>شروط الاستخدام</button></div></div></div><div className="border-t border-blue-50 py-4 text-center text-sm text-slate-400">© {new Date().getFullYear()} صيدلية حياة المجد — جميع الحقوق محفوظة</div></footer></>}
    {chatOpen&&<ChatbotPanel onClose={()=>setChatOpen(false)}/>}
    {policy&&<PolicyModal type={policy} onClose={()=>setPolicy(null)}/>}
  </main>
}

function ChatbotPanel({onClose}:{onClose:()=>void}){
  const [message,setMessage]=useState('');
  const [messages,setMessages]=useState<{role:'user'|'assistant';text:string}[]>([]);
  const [loading,setLoading]=useState(false);
  const send=async(text=message)=>{const clean=text.trim();if(!clean||loading)return;const history=[...messages,{role:'user' as const,text:clean}];setMessages(history);setMessage('');setLoading(true);try{const client=await getSupabase();const {data,error}=await client.functions.invoke('pharmacy-chat',{body:{message:clean,history:history.slice(-8)}});if(error)throw error;setMessages(current=>[...current,{role:'assistant',text:String(data?.reply||'تعذر الحصول على إجابة الآن.')}])}catch{setMessages(current=>[...current,{role:'assistant',text:'عذرًا، المساعد غير متاح مؤقتًا. يمكنك التواصل معنا عبر واتساب.'}])}finally{setLoading(false)}};
  return <div className="fixed inset-0 z-[85] flex items-end justify-end bg-slate-950/25 p-0 backdrop-blur-[2px] sm:p-5" onClick={onClose}><section role="dialog" aria-modal="true" aria-label="مساعد صيدلية حياة المجد" onClick={e=>e.stopPropagation()} className="flex h-[min(78vh,620px)] w-full flex-col overflow-hidden rounded-t-[2rem] bg-white shadow-2xl sm:w-[390px] sm:rounded-[2rem]"><header className="flex items-center gap-3 bg-[#0b4b84] p-4 text-white"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/15"><Bot size={23}/></span><div className="flex-1"><b className="block">مساعد حياة المجد</b><small className="text-blue-100">مساعد ذكي للمنتجات والخدمات</small></div><button onClick={onClose} aria-label="إغلاق المساعد" className="grid h-9 w-9 place-items-center rounded-full bg-white/10"><X size={19}/></button></header><div className="flex-1 overflow-y-auto bg-[#f5f9ff] p-4"><div className="max-w-[88%] rounded-2xl rounded-tr-sm bg-white p-4 text-sm leading-7 shadow-sm"><b className="block text-[#0b4b84]">أهلًا بك في صيدلية حياة المجد 👋</b><span className="text-slate-600">اسألني عن المنتجات، الأسعار، التوفر، الأقسام أو طريقة الطلب والتوصيل.</span></div><div className="mt-4 flex flex-wrap gap-2">{['أبحث عن منتج للبشرة','ما المنتجات المتوفرة؟','كيف أطلب؟'].map(item=><button key={item} onClick={()=>void send(item)} className="rounded-full border border-blue-200 bg-white px-3 py-2 text-xs font-bold text-[#0b4b84]">{item}</button>)}</div>{messages.map((item,i)=><div key={`${item.role}-${i}`} className={`mt-4 max-w-[88%] whitespace-pre-wrap rounded-2xl p-3 text-sm leading-6 ${item.role==='user'?'mr-auto rounded-tl-sm bg-[#0b4b84] text-white':'rounded-tr-sm bg-white text-slate-700 shadow-sm'}`}>{item.text}</div>)}{loading&&<div className="mt-4 w-fit rounded-2xl bg-white px-4 py-3 text-sm text-slate-500 shadow-sm">جارٍ البحث في منتجات الصيدلية…</div>}</div><form onSubmit={e=>{e.preventDefault();void send()}} className="flex gap-2 border-t border-blue-100 bg-white p-3"><input value={message} onChange={e=>setMessage(e.target.value)} disabled={loading} maxLength={500} placeholder="اكتب سؤالك هنا..." aria-label="رسالة إلى المساعد" className="min-w-0 flex-1 rounded-xl border border-blue-100 bg-blue-50/50 px-4 py-3 outline-none focus:border-blue-400 disabled:opacity-60"/><button disabled={loading||!message.trim()} aria-label="إرسال" className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#0b4b84] text-white disabled:opacity-50"><Send size={20}/></button></form></section></div>
}

function Checkout({items,total,onClose,onSuccess}:{items:{product:Product;qty:number}[];total:number;onClose:()=>void;onSuccess:(id:string)=>void}){
  const [data,setData]=useState({customer_name:'',phone:'',address:'',notes:'',area:deliveryAreas[0].name}); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const delivery=deliveryAreas.find(a=>a.name===data.area)?.fee||0; const grandTotal=total+delivery;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');const orderId=crypto.randomUUID();const {area,...customer}=data;const payload={id:orderId,...customer,address:`${area} — ${customer.address}`,total:grandTotal,items:items.map(({product,qty})=>({id:product.id,name:product.name,price:product.price,qty}))};const client=await getSupabase();const {error:dbError}=await client.from('orders').insert(payload);setSaving(false);if(dbError){setError('تعذر إرسال الطلب، تحقق من البيانات وحاول مرة أخرى');return}onSuccess(orderId)};
  return <div className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/50 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" onClick={onClose}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-[2rem] bg-white p-6 shadow-2xl sm:rounded-[2rem] md:p-8"><div className="flex items-center justify-between"><div><small className="font-bold text-[#168bc5]">الخطوة الأخيرة</small><h2 className="text-2xl font-black">بيانات التوصيل</h2></div><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full bg-blue-50"><X/></button></div><div className="mt-6 space-y-4"><Field label="الاسم الكامل *"><input value={data.customer_name} onChange={e=>setData({...data,customer_name:e.target.value})} required minLength={2} autoComplete="name" placeholder="الاسم الكامل"/></Field><Field label="رقم الهاتف *"><input value={data.phone} onChange={e=>setData({...data,phone:e.target.value})} required minLength={8} inputMode="tel" autoComplete="tel" placeholder="07XX XXX XXXX"/></Field><Field label="منطقة التوصيل *"><select value={data.area} onChange={e=>setData({...data,area:e.target.value})}>{deliveryAreas.map(a=><option key={a.name} value={a.name}>{a.name} — {money(a.fee)}</option>)}</select></Field><Field label="عنوان التوصيل *"><textarea value={data.address} onChange={e=>setData({...data,address:e.target.value})} required minLength={5} rows={3} autoComplete="street-address" placeholder="المدينة، المنطقة، أقرب نقطة دالة"/></Field><Field label="ملاحظات"><textarea value={data.notes} onChange={e=>setData({...data,notes:e.target.value})} rows={2} placeholder="أي ملاحظات تخص الطلب (اختياري)"/></Field></div><div className="mt-6 rounded-2xl bg-blue-50 p-4"><div className="flex justify-between text-sm text-slate-500"><span>المنتجات</span><span>{money(total)}</span></div><div className="mt-2 flex justify-between text-sm text-slate-500"><span>التوصيل</span><span>{money(delivery)}</span></div><div className="mt-3 flex justify-between border-t border-blue-100 pt-3 text-xl font-black"><span>الإجمالي</span><span>{money(grandTotal)}</span></div><p className="mt-2 text-xs text-slate-500">الدفع عند الاستلام</p></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-600">{error}</p>}<button disabled={saving} className="mt-5 w-full rounded-2xl bg-[#0b4b84] py-4 font-black text-white disabled:opacity-60">{saving?'جارٍ تسجيل الطلب...':'تأكيد الطلب'}</button><p className="mt-3 text-center text-xs text-slate-400">بياناتك تستخدم لتنفيذ هذا الطلب فقط.</p></form></div>
}

function PolicyModal({type,onClose}:{type:Exclude<Policy,null>;onClose:()=>void}){const content={privacy:['سياسة الخصوصية','نجمع الاسم ورقم الهاتف والعنوان لتنفيذ الطلب والتواصل بشأنه فقط. لا نبيع بيانات العملاء أو نشاركها لأغراض إعلانية.'],returns:['الاستبدال والاسترجاع','يمكن طلب الاستبدال خلال 7 أيام للمنتج غير المفتوح وبحالته الأصلية. لا تُسترجع المنتجات المفتوحة حفاظًا على السلامة الصحية، إلا عند وجود عيب مثبت.'],terms:['شروط الاستخدام','الأسعار والمخزون قابلة للتحديث. يتم تثبيت الطلب بعد تواصل فريق المتجر مع العميل. المعلومات المعروضة للعناية العامة ولا تغني عن استشارة الطبيب أو الصيدلاني.']} as const;return <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4" onClick={onClose}><section onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-[2rem] bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{content[type][0]}</h2><button onClick={onClose} aria-label="إغلاق"><X/></button></div><p className="mt-5 text-lg leading-8 text-slate-600">{content[type][1]}</p><button onClick={onClose} className="mt-6 w-full rounded-xl bg-[#0b4b84] py-3 font-bold text-white">فهمت</button></section></div>}

async function optimizeImage(file:File){return new Promise<Blob>((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,1200/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')?.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('image')),'image/webp',.82)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url})}

function Admin({products,categories,hasMore,loadingProducts,onLoadMore,onSearch,onSave,onDelete,onSaveCategory,onDeleteCategory}:{products:Product[];categories:StoreCategory[];hasMore:boolean;loadingProducts:boolean;onLoadMore:()=>Promise<void>;onSearch:(value:string)=>void;onSave:(p:Product[],token:string)=>void;onDelete:(id:string,token:string)=>void;onSaveCategory:(category:Partial<StoreCategory>,token:string)=>Promise<boolean>;onDeleteCategory:(id:string,token:string)=>void}){
  const empty:Omit<Product,'id'>={name:'',category:categories[0]?.name||'العناية بالبشرة',price:0,oldPrice:undefined,stock:0,image:'',description:'',featured:false};
  const [form,setForm]=useState<Omit<Product,'id'>>(empty); const [editing,setEditing]=useState<string|null>(null); const [adminQuery,setAdminQuery]=useState(''); const [uploading,setUploading]=useState(false);
  const [categoryForm,setCategoryForm]=useState({id:'',name:'',sort_order:0});
  const [orders,setOrders]=useState<Order[]>([]);
  const [adminToken,setAdminToken]=useState(()=>typeof window==='undefined'?'':sessionStorage.getItem('hayat-admin-session')||''); const [pin,setPin]=useState(''); const [authMessage,setAuthMessage]=useState('');
  useEffect(()=>{if(!adminToken)return;let previous='';const load=async()=>{const client=await getSupabase();const {data,error}=await client.rpc('admin_list_orders',{session_token:adminToken});if(error){sessionStorage.removeItem('hayat-admin-session');setAdminToken('');return}const next=(data||[]) as Order[];if(previous&&next[0]?.id!==previous&&'Notification'in window&&Notification.permission==='granted')new Notification('طلب جديد في صيدلية حياة المجد',{body:`طلب من ${next[0]?.customer_name||'عميل جديد'}`});previous=next[0]?.id||'';setOrders(next)};void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer)},[adminToken]);
  const revenue=useMemo(()=>products.reduce((s,p)=>s+p.price*p.stock,0),[products]);
  const visible=products;
  const uploadImage=async(file:File)=>{setUploading(true);setAuthMessage('');try{const blob=await optimizeImage(file);const client=await getSupabase();const {data,error}=await client.functions.invoke('upload-product-image',{body:blob,headers:{'x-admin-session':adminToken,'x-file-type':'image/webp'}});if(error||!data?.url)throw error||new Error('upload');setForm(current=>({...current,image:data.url}))}catch{setAuthMessage('تعذر رفع الصورة. تأكد من صلاحية جلسة الإدارة وحجم الملف.')}finally{setUploading(false)}};
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.image||form.price<=0)return;const clean={...form,name:form.name.trim(),description:form.description.trim()};const next=editing?products.map(p=>p.id===editing?{...clean,id:editing}:p):[{...clean,id:crypto.randomUUID()},...products];onSave(next,adminToken);setForm(empty);setEditing(null)};
  const edit=(p:Product)=>{setEditing(p.id);setForm({...p});window.scrollTo({top:0,behavior:'smooth'})};
  const updateOrder=async(id:string,status:string)=>{const client=await getSupabase();const {error}=await client.rpc('admin_update_order',{session_token:adminToken,order_id:id,new_status:status});if(!error)setOrders(current=>current.map(o=>o.id===id?{...o,status}:o))};
  if(!adminToken)return <section className="mx-auto grid min-h-[70vh] max-w-lg place-items-center px-4"><form onSubmit={async e=>{e.preventDefault();const client=await getSupabase();const {data,error}=await client.rpc('admin_login',{candidate:pin});if(error||!data){setAuthMessage('الرمز غير صحيح، وقد يتم إيقاف المحاولات مؤقتًا للحماية');setPin('');return}sessionStorage.setItem('hayat-admin-session',data);setAdminToken(data);setAuthMessage('')}} className="w-full rounded-[2rem] border border-blue-100 bg-white p-7 text-center shadow-xl md:p-10"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-[#0b4b84]"><ShieldCheck size={30}/></span><h1 className="mt-5 text-3xl font-black">رمز الإدارة</h1><p className="mt-2 text-slate-500">أدخل كلمة المرور المكوّنة من 6 أرقام.</p><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} required minLength={6} inputMode="numeric" autoComplete="current-password" type="password" placeholder="••••••" className="mt-6 w-full rounded-xl border border-blue-100 bg-blue-50/50 px-4 py-3 text-center text-2xl font-black tracking-[.5em] outline-none focus:border-blue-400"/><button className="mt-3 w-full rounded-xl bg-[#0b4b84] py-3 font-black text-white">فتح لوحة الإدارة</button>{authMessage&&<p className="mt-4 text-sm font-bold text-red-500">{authMessage}</p>}<p className="mt-5 text-xs text-slate-400">تُغلق الجلسة تلقائيًا بعد 30 دقيقة.</p></form></section>;
  return <section className="mx-auto max-w-7xl px-3 py-6 md:px-8 md:py-12">
    <div className="mb-6 flex items-start justify-between gap-4 md:mb-8"><div><div className="flex items-center gap-2"><span className="text-sm font-bold text-[#168bc5]">لوحة التحكم</span><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700"><ShieldCheck size={13}/> اتصال محمي</span></div><h1 className="mt-1 text-2xl font-black md:text-4xl">إدارة المنتجات</h1><p className="mt-2 hidden text-slate-500 sm:block">أضف المنتجات وعدّل المخزون والأسعار من مكان واحد.</p></div><div className="flex flex-col gap-2 sm:flex-row"><button onClick={()=>{'Notification'in window?void Notification.requestPermission():setAuthMessage('التنبيهات غير مدعومة في هذا المتصفح')}} className="flex items-center justify-center gap-2 rounded-xl border border-blue-100 bg-white px-4 py-2 text-sm font-bold"><Bell size={16}/> تنبيهات الطلبات</button><button onClick={()=>{sessionStorage.removeItem('hayat-admin-session');setAdminToken('')}} className="rounded-xl border border-blue-100 bg-white px-4 py-2 text-sm font-bold">خروج آمن</button></div></div>
    <div className="mb-6 grid grid-cols-2 gap-3 md:mb-8 md:grid-cols-3 md:gap-4"><Stat label="المنتجات المعروضة" value={String(products.length)} icon={<ShoppingBag/>}/><Stat label="قطع في الصفحة" value={String(products.reduce((s,p)=>s+p.stock,0))} icon={<PackagePlus/>}/><div className="col-span-2 md:col-span-1"><Stat label="قيمة الصفحة" value={money(revenue)} icon={<Sparkles/>}/></div></div>
    <section className="mb-6 overflow-hidden rounded-[1.8rem] bg-white shadow-sm md:mb-8"><div className="border-b border-blue-50 p-5 md:p-6"><small className="font-bold text-[#168bc5]">تنظيم المتجر</small><h2 className="text-xl font-black">إدارة الأقسام</h2><p className="mt-1 text-sm text-slate-500">أضف قسمًا جديدًا أو عدّل اسمه وترتيبه. عند تعديل الاسم تتحدث منتجاته تلقائيًا.</p></div><form onSubmit={async e=>{e.preventDefault();if(!categoryForm.name.trim())return;const ok=await onSaveCategory({id:categoryForm.id||undefined,name:categoryForm.name.trim(),sort_order:categoryForm.sort_order},adminToken);if(ok)setCategoryForm({id:'',name:'',sort_order:0})}} className="grid gap-3 border-b border-blue-50 p-5 sm:grid-cols-[1fr_140px_auto] md:p-6"><Field label="اسم القسم"><input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} required minLength={2} maxLength={60} placeholder="مثال: المكملات الغذائية"/></Field><Field label="الترتيب"><input type="number" min="0" max="999" value={categoryForm.sort_order} onChange={e=>setCategoryForm({...categoryForm,sort_order:+e.target.value})}/></Field><div className="flex items-end gap-2"><button className="h-[42px] flex-1 rounded-xl bg-[#0b4b84] px-5 font-black text-white">{categoryForm.id?'حفظ التعديل':'إضافة القسم'}</button>{categoryForm.id&&<button type="button" onClick={()=>setCategoryForm({id:'',name:'',sort_order:0})} className="h-[42px] rounded-xl bg-slate-100 px-4 font-bold">إلغاء</button>}</div></form><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-3 md:p-6">{categories.map(item=>{const Icon=categoryIconMap[item.name]||PackagePlus;return <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-blue-50 bg-[#fbfdff] p-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e9f3ff] text-[#168bc5]">{item.name==='العناية بالشعر'?<HairIcon className="h-6 w-6"/>:<Icon size={20}/>}</span><div className="min-w-0 flex-1"><b className="block truncate">{item.name}</b><small className="text-slate-400">الترتيب: {item.sort_order}</small></div><button onClick={()=>setCategoryForm({id:item.id,name:item.name,sort_order:item.sort_order})} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">تعديل</button><button onClick={()=>void onDeleteCategory(item.id,adminToken)} aria-label={`حذف قسم ${item.name}`} className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-500"><Trash2 size={16}/></button></div>})}</div></section>
    <div className="grid items-start gap-6 lg:grid-cols-[430px_1fr]">
      <form onSubmit={submit} className="overflow-hidden rounded-[1.8rem] bg-white shadow-sm lg:sticky lg:top-24">
        <div className="border-b border-blue-50 p-5 md:p-6"><div className="flex items-center justify-between"><div><small className="font-bold text-[#168bc5]">{editing?'وضع التعديل':'منتج جديد'}</small><h2 className="text-xl font-black">{editing?'تعديل بيانات المنتج':'إضافة منتج'}</h2></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#0b4b84]"><PackagePlus/></span></div></div>
        <div className="space-y-4 p-5 md:p-6">
          <div className="flex items-center gap-4 rounded-2xl border border-dashed border-blue-200 bg-blue-50/40 p-3">{form.image?<img src={form.image} alt="معاينة المنتج" className="h-24 w-24 rounded-xl object-cover"/>:<span className="grid h-24 w-24 shrink-0 place-items-center rounded-xl bg-white text-blue-200"><ShoppingBag size={32}/></span>}<div><b className="block">معاينة الصورة</b><small className="text-slate-500">أضف رابط صورة واضحة ومربعة للحصول على أفضل نتيجة.</small></div></div>
          <Field label="اسم المنتج *"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="مثال: كريم ترطيب عميق"/></Field>
          <Field label="التصنيف *"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></Field>
          <div className="grid grid-cols-2 gap-3"><Field label="السعر الحالي *"><input type="number" min="1" value={form.price||''} onChange={e=>setForm({...form,price:+e.target.value})} required placeholder="40000"/></Field><Field label="السعر قبل الخصم"><input type="number" min="1" value={form.oldPrice||''} onChange={e=>setForm({...form,oldPrice:e.target.value?+e.target.value:undefined})} placeholder="اختياري"/></Field></div>
          <Field label="الكمية في المخزون"><input type="number" min="0" value={form.stock||''} onChange={e=>setForm({...form,stock:+e.target.value})} placeholder="0"/></Field>
          <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-blue-200 bg-blue-50 py-3 font-bold text-[#0b4b84]"><Camera size={19}/>{uploading?'جارٍ ضغط الصورة ورفعها...':'رفع صورة من الجهاز'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadImage(file)}}/></label>{authMessage&&<p className="text-sm font-bold text-red-500">{authMessage}</p>}
          <Field label="أو رابط صورة المنتج *"><input type="text" value={form.image} onChange={e=>setForm({...form,image:e.target.value})} required placeholder="https://... أو ارفع صورة أعلاه"/></Field>
          <Field label="وصف المنتج"><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="اكتب وصفًا مختصرًا يوضح فائدة المنتج وطريقة استخدامه"/></Field>
          <label className="flex cursor-pointer items-center justify-between rounded-xl border border-blue-100 bg-blue-50/40 p-3"><span><b className="block text-sm">منتج مميز</b><small className="text-slate-500">إظهاره ضمن اختيارات المتجر</small></span><input type="checkbox" checked={!!form.featured} onChange={e=>setForm({...form,featured:e.target.checked})} className="h-5 w-5 accent-[#0b4b84]"/></label>
          <button disabled={uploading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0b4b84] py-3.5 font-black text-white shadow-lg shadow-blue-100 disabled:opacity-60"><Plus size={19}/>{editing?'حفظ التعديلات':'إضافة المنتج'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="w-full text-sm font-bold text-slate-500">إلغاء التعديل</button>}
        </div>
      </form>
      <div className="overflow-hidden rounded-[1.8rem] bg-white shadow-sm"><div className="border-b border-blue-50 p-5 md:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">المنتجات</h2><small className="text-slate-500">{visible.length} منتج في هذه الصفحة</small></div><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-blue-300" size={18}/><input value={adminQuery} onChange={e=>{setAdminQuery(e.target.value);onSearch(e.target.value)}} placeholder="ابحث في جميع المنتجات" className="w-full rounded-xl border border-blue-100 bg-blue-50/40 py-2.5 pr-10 pl-3 outline-none sm:w-64"/></div></div></div>
        <div className="divide-y divide-blue-50">{visible.map(p=><div key={p.id} className="grid grid-cols-[64px_1fr_auto] items-center gap-3 p-4 md:grid-cols-[72px_1fr_auto_auto] md:p-5"><img src={p.image} alt="" loading="lazy" decoding="async" className="h-16 w-16 rounded-xl object-cover md:h-[72px] md:w-[72px]"/><div className="min-w-0"><div className="flex items-center gap-2"><b className="truncate">{p.name}</b>{p.featured&&<Star size={14} className="shrink-0 text-[#3b82f6]" fill="currentColor"/>}</div><span className="block text-sm text-slate-500">{p.category}</span><span className={`mt-1 inline-block text-xs font-bold ${p.stock<5?'text-red-500':'text-emerald-600'}`}>{p.stock<5?'مخزون منخفض':'متوفر'} • {p.stock} قطعة</span></div><b className="hidden text-sm md:block">{money(p.price)}</b><div className="flex items-center gap-2"><button onClick={()=>edit(p)} className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700">تعديل</button><button onClick={()=>onDelete(p.id,adminToken)} aria-label="حذف" className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-500"><Trash2 size={17}/></button></div></div>)}{!visible.length&&<div className="p-12 text-center text-slate-400"><Search className="mx-auto mb-3"/>لا توجد منتجات مطابقة</div>}</div>{hasMore&&<button onClick={()=>void onLoadMore()} disabled={loadingProducts} className="m-5 w-[calc(100%-2.5rem)] rounded-xl border border-blue-100 bg-blue-50 py-3 font-black text-[#0b4b84] disabled:opacity-60">{loadingProducts?'جارٍ التحميل...':'تحميل منتجات أكثر'}</button>}
      </div>
    </div>
    <div className="mt-8 overflow-hidden rounded-[1.8rem] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-blue-50 p-5 md:p-6"><div><small className="font-bold text-[#168bc5]">طلبات المتجر</small><h2 className="text-xl font-black">متابعة الطلبات</h2></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-600">{orders.filter(o=>o.status==='جديد').length} جديد</span></div><div className="divide-y divide-blue-50">{orders.map(o=><article key={o.id} className="grid gap-4 p-5 md:grid-cols-[1fr_auto] md:p-6"><div><div className="flex flex-wrap items-center gap-2"><b className="text-lg">{o.customer_name}</b><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">#{o.id.slice(0,8)}</span><span className="text-sm text-slate-400">{new Date(o.created_at).toLocaleDateString('ar-IQ')}</span></div><a href={`tel:${o.phone}`} className="mt-2 inline-block font-bold text-[#168bc5]">{o.phone}</a><p className="mt-1 text-sm text-slate-600">{o.address}</p><p className="mt-2 text-sm text-slate-500">{o.items.map(i=>`${i.name} × ${i.qty}`).join('، ')}</p>{o.notes&&<p className="mt-2 rounded-xl bg-slate-50 p-2 text-sm text-slate-500">ملاحظة: {o.notes}</p>}</div><div className="flex items-center justify-between gap-4 md:flex-col md:items-end"><b className="text-lg">{money(Number(o.total))}</b><select value={o.status} onChange={e=>void updateOrder(o.id,e.target.value)} className="rounded-xl border border-blue-100 bg-blue-50/50 px-3 py-2 text-sm font-bold outline-none">{['جديد','قيد التجهيز','خرج للتوصيل','مكتمل','ملغي'].map(s=><option key={s}>{s}</option>)}</select></div></article>)}{!orders.length&&<div className="p-10 text-center text-slate-400"><Truck className="mx-auto mb-2"/>لا توجد طلبات حتى الآن</div>}</div></div>
  </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold">{label}<div className="mt-1 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-blue-100 [&>*]:bg-blue-50/40 [&>*]:px-3 [&>*]:py-2.5 [&>*]:outline-none focus-within:[&>*]:border-blue-400">{children}</div></label>}
function Stat({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-[#0988c8]">{icon}</span><div><small className="text-slate-500">{label}</small><b className="block text-xl">{value}</b></div></div>}
